language: php

php:
 - 5.3.3
 - 5.3
 - 5.4
 - 5.5
 - 5.6
 - hhvm

before_script:
# On PHP 5.3.3 we require "--prefer-source" option because of missing openssl issue
 - if [ "$TRAVIS_PHP_VERSION" = "5.3.3" ]; then prefer_source="--prefer-source"; else prefer_source=""; fi
 - composer self-update -n
 - composer install --dev -n $prefer_source

script:
 - php vendor/bin/phpunit --verbose --coverage-clover=coverage.clover
 - wget "https://scrutinizer-ci.com/ocular.phar"
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

notifications:
  email: false
